HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from room.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('account/', include('accountss.urls')),
    path('admins/', include('admins.urls')),
    path('social/', include('social_media.urls') ),
    path('', home, name='home'),
    path('room/', include('room.urls')),
    path('restaurant/', restaurant, name='restaurant'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('accounts/', include('allauth.urls')),
    path('social/', include('social_django.urls', namespace='social')),
    path('gym/', include('gym.urls')),
    path('', include('paypal.standard.ipn.urls')),
    path('hall/', include('Hall.urls')),
    path('spa/', include('Spa.urls')),
    
    
]


# your existing URL patterns...

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Spa/urls.py
from django.urls import path
from .views import *

app_name = 'spa'

urlpatterns = [
    path('', ServiceListView.as_view(), name='service_list'),
    path('booking/create/', SpaBookingCreateView.as_view(), name='create_booking'),
    path('bookings/', BookingListView.as_view(), name='booking_list'),
    path('booking/cancel/<int:booking_id>/', CancelBookingView.as_view(), name='cancel_booking'),
    path('book/<str:item_type>/<int:item_id>/', SpaBookingCreateView.as_view(), name='spa_booking_create'),
    path('paypal-return/', SpaPayPalReturnView.as_view(), name='spa_paypal_return'),
    path('paypal-cancel/', SpaPayPalCancelView.as_view(), name='spa_paypal_cancel'),
]

accountss/urls.py
from accountss.views import *
from django.urls import path, include


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='signup'),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('profile/change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
]

Hall/models.py
from django.db import models
from accountss.models import Custom_user as User
from django.utils import timezone
import datetime

class Hall_Category(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Hall(models.Model):
    Hall_STATUS_CHOICES = (
        ('available', 'Available'),
        ('booked', 'Booked'),
    )
    hall_type = models.ForeignKey(Hall_Category, on_delete=models.CASCADE, default=1)
    hall_number = models.CharField(max_length=20, default='000')
    description = models.TextField()
    price_per_hour = models.DecimalField(max_digits=10, decimal_places=2)
    capacity = models.IntegerField()
    image = models.ImageField(upload_to='media/hall_images/', blank=True)
    floor = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=Hall_STATUS_CHOICES, default='available')


    def __str__(self):
        return f"{self.hall_number} - {self.hall_type}"

class Hall_Booking(models.Model):
    Booking_STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, null=True)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100,blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(default=datetime.time(6, 0),null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    amount_due = models.DecimalField(max_digits=10, decimal_places=2)
    is_paid = models.BooleanField(default=False)
    occupied = models.BooleanField(default=False)
    email2 = models.EmailField(null=True, blank=True)
    id_image = models.ImageField(upload_to='media/id_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    tx_ref = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=20, choices=Booking_STATUS_CHOICES, default='pending')

    def __str__(self):
        user_display = self.user.username if self.user else self.full_name
        return f"{user_display} - {self.hall.hall_type}"




class Hall_Payment(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    )
    PAYMENT_METHOD_CHOICES = (
        ('chapa', 'Chapa'),
        ('paypal', 'PayPal'),
        ('cash', 'Cash'),
    )
    booking = models.OneToOneField(Hall_Booking, on_delete=models.CASCADE)
    payment_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    receipt_pdf = models.FileField(upload_to='media/receipts/', blank=True, null=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default='chapa')
    
    def __str__(self):
        return f"Payment {self.id} - {self.status}"

accountss/forms.py
from django import forms
from django.forms import ModelForm  # Import the ModelForm class
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from accountss.models import Custom_user
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

from django.core.validators import RegexValidator


class CustomUserCreationForm(UserCreationForm):
    username_regex = RegexValidator(
        regex=r'^.{2,10}$',
        message="Username must be 2 to 10 characters long."
    )
    username = forms.CharField(validators=[username_regex])
    name_regex = RegexValidator(
        regex=r'^[a-zA-Z]{2,15}$',
        message="Name must be at least 2 letters and atmost 15 letters long and contain only letters."
    )
    first_name = forms.CharField(validators=[name_regex])
    last_name = forms.CharField(validators=[name_regex])

    class Meta:
        model = Custom_user
        fields = ['username', 'first_name', 'last_name', 'email', 'country', 'profile_picture', 'phone_number']

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].widget = forms.TextInput(attrs={'placeholder': '+2519xxxxxxxx or +2517xxxxxxxx'})

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Custom_user.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if Custom_user.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already in use.")
        return username
    



class CustomUserUpdateForm(forms.ModelForm):
    username_regex = RegexValidator(
        regex=r'^.{2,15}$',
        message="Username must be 2 to 10 characters long."
    )
    username = forms.CharField(validators=[username_regex])
    name_regex = RegexValidator(
        regex=r'^[a-zA-Z]{2,10}$',
        message="Name must be at least 2 letters and atmost 10 letters long and contain only letters."
    )
    first_name = forms.CharField(validators=[name_regex])
    last_name = forms.CharField(validators=[name_regex])

    class Meta:
        model = Custom_user
        fields = ['username', 'first_name', 'last_name', 'email', 'country',  'profile_picture', 'phone_number']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Custom_user.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise ValidationError("This email address is already in use.")
        return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if Custom_user.objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise ValidationError("This username is already in use.")
        return username

accountss/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView
from django.views.generic.edit import CreateView
from accountss.forms import *

from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib import messages
from django.urls import reverse
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str,DjangoUnicodeDecodeError
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import get_user_model, login
from config import BASE_URL
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponse
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, logout


from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.hashers import make_password
from .models import Custom_user

# class CustomUserAdmin(UserAdmin):
#     model = Custom_user

#     def save_model(self, request, obj, form, change):
#         if form.cleaned_data['password']:
#             obj.password = make_password(form.cleaned_data['password'])
#         super().save_model(request, obj, form, change)

# # Modify this instead of registering again
# admin.site.unregister(Custom_user)  # If needed, to clear the existing registration
# admin.site.register(Custom_user, CustomUserAdmin)





from django.utils import timezone  

class CustomLoginView(LoginView):
    template_name = 'accountss/login.html'
    
    def get_success_url(self):
        user = self.request.user
        if not user.is_active:
            messages.error(self.request, 'Please verify your email address to complete the login.')
            return redirect('login')
        if user.first_login and user.role == 'customer':
            user.first_login = False
            user.save()
            update_session_auth_hash(self.request, user)  # Update the session, because the backend hashes some of the user session data.
            messages.info(self.request, 'Please complete your profile.')
            return reverse_lazy('profile_update', kwargs={'pk': user.pk})
        elif user.role == 'owner' or user.role == 'manager' or user.role == 'receptionist':
            return reverse_lazy('admins:admin_dashboard')
        elif user.role == 'admin':
            return reverse_lazy('admin:index')
        else:  
            return reverse_lazy('home')

    def form_invalid(self, form):
        messages.error(self.request, "Invalid username or password")
        return super().form_invalid(form)

    def form_valid(self, form):
        user = form.get_user()
        user.last_login = timezone.now()
        user.save(update_fields=['last_login'])
        return super().form_valid(form)



        
from .tokens import account_activation_token

class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accountss/signup.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save(commit=False)
        if user.role == 'customer':  # Assuming 'customer' is the role name
            user.is_active = False
            user.save()
            self.send_verification_email(user)
            messages.success(self.request, 'Please verify your email address to complete the registration.')
        else:
            user.is_active = True
            user.save()
        return super().form_valid(form)

    def send_verification_email(self, user):
        uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
        activate_url = f"{BASE_URL}{reverse_lazy('activate', kwargs={'uidb64': uidb64, 'token': account_activation_token.make_token(user)})}"
        subject = 'Activate your account'
        html_content = render_to_string('accountss/acc_active_email.html', {
            'user': user,
            'activate_url': activate_url,
        })

        email = EmailMultiAlternatives(
            subject=subject,
            body='Activation link',
            from_email='adarhotel33@gmail.com',
            to=[user.email],
        )
        email.attach_alternative(html_content, "text/html")
        email.send()


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Custom_user.objects.get(pk=uid)
    except (DjangoUnicodeDecodeError, TypeError, ValueError, OverflowError, Custom_user.DoesNotExist) as e:
        user = None
        print(f"Error decoding UID: {e}")
    
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been activated successfully.')
        return redirect('login')
    else:
        return HttpResponse('Activation link is invalid!')


def home(request):
    return render(request, 'room/home.html')


from django.contrib.auth.views import LogoutView

class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('login')
    template_name = None



class ProfileDetailView(LoginRequiredMixin,DetailView):
    model = Custom_user
    template_name = 'accountss/profile_detail.html'
    context_object_name = 'profile'
    

class ProfileUpdateView(LoginRequiredMixin,UpdateView):
    model = Custom_user
    form_class = CustomUserUpdateForm
    template_name = 'accountss/profile_update.html'
    

    def get_success_url(self):
        user = self.request.user
        user.first_login = False
        return reverse_lazy('profile_detail', kwargs={'pk': self.object.pk})
    



class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'accountss/change_password.html'
    form_class = PasswordChangeForm
    
    def get_success_url(self):
        return reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)  # Important, to update the session with the new password
        logout(self.request)
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.user = self.request.user
        return form

accountss/templates/accountss/acc_active_email.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Email Verification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f3f3;
        }
        .container {
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .header {
            background-color: #e1ff00;
            color: rgb(0, 0, 0);
            text-align: center;
            padding: 20px 0;
            border-radius: 8px 8px 0 0;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .content {
            padding: 20px;
            color: #333333;
        }
        .content p {
            margin: 0 0 10px;
        }
        .button {
            display: inline-block;
            padding: 10px 20px;
            margin: 20px 0;
            font-size: 16px;
            color: white;
            background-color: #0fd945;
            text-decoration: none;
            border-radius: 5px;
            text-align: center;
        }
        .footer {
            text-align: center;
            padding: 10px 0;
            font-size: 12px;
            color: #777777;
            border-top: 1px solid #dddddd;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Email Verification</h1>
        </div>
        <div class="content">
            <h3>Dear {{ user.first_name }},</h3>
            <p>Please verify your email address by clicking the link below:</p>
            <a href="{{ activate_url }}" class="button">Verify Email</a>
        </div>
        <div class="footer">
            <p>Thank you for registering with our Hotel!</p>
            <p>If you did not sign up for this account, please disregard this email.</p>
        </div>
    </div>
</body>
</html>

accountss/templates/accountss/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon-32x32.png' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style2.css' %}">
  <link rel="stylesheet" href="{% static 'css/style6.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@355&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  <title>ADAR</title>


<style>
    .goog-te-gadget {
      font-family: Montserrat, 'Open Sans', sans-serif!important;
    }
    .VIpgJd-ZVi9od-ORHb-OEVmcd{
  display: none;

}


body {
  top: 0px !important; 

}
.goog-te-gadget-simple a {
  color: rgba(0, 0, 0, 0.811)!important;
  text-decoration: none!important;
  font-weight: bold;
}

    .goog-te-gadget-simple  {
      background-color: rgba(255, 255, 255, 0.885)!important;
      border: 1px solid rgba(255,255,255,0.50) !important;
      padding: 2px!important;
      border-radius: 4px!important;
      font-size: .8rem!important;
      line-height:2rem!important;
      display: inline-block;
      cursor: pointer;
      zoom: 1;
    }
    
    .goog-te-gadget-icon {
      display: none;
    }

    .goog-te-banner-frame.skiptranslate {
      display: none !important;
    }

    body {
      top: 0px !important;
    }

    .navbar-toggler-icon {
      background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3e%3cpath stroke='rgba(255, 255, 0, 1)' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
    }

    .dropdown-toggle-no-caret::after {
      display: none !important;
    }

    .dropdown:hover .dropdown-menu {
      display: block;
      margin-top: 0;
    }

    .transparent-dropdown {
      background-color: rgba(0, 0, 0, 0.4) !important;
      border-radius: 10px;
      margin-top: 5rem;
    }

    .dropdown-item:hover {
      background-color: transparent;
      color: rgb(239, 12, 12) !important;
    }

    a.dropdown-item:hover {
      color: rgb(241, 238, 238) !important;
    }

    .navbar-nav .nav-link {
      display: flex;
      align-items: center;
    }

    .dropdown-menu {
      padding: 0.5rem 0;
    }

    .navbar-nav .btn.p-0 {
      display: flex;
      align-items: center;
    }

    #google_translate_element {
      position: fixed;
      bottom: 10px;
      right: 10px;
      z-index: 1000;
    }
  </style>
</head>

<body>
  <nav class="navbar bg-body-tertiary navbar-expand-md fixed-top">
    <div class="container">
      <a class="navbar-brand text-warning" href="{% url 'home' %}">ADAR</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myTogglerNav"
        aria-controls="myTogglerNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="myTogglerNav">
        <div class="navbar-nav ml-auto pt-1">
          <a class="nav-item nav-link text-warning" href="{% url 'home' %}">Home</a>
          <a class="nav-item nav-link text-warning" href="{% url 'about' %}">About</a>
          
          <div class="dropdown ml-3">
            <a style="outline: none;" class="btn  pt-2 text-warning dropdown-toggle-no-caret nav-link"
              id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">Room</a>
            <div class="dropdown-menu transparent-dropdown" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item nav-link text-warning " href="{% url 'rooms' %}">View Rooms</a>
              {% if user.is_authenticated %}
              <a class="dropdown-item nav-link text-warning" href="{% url 'bookings' %}">My Bookings</a>
              <a class="dropdown-item nav-link text-warning" href="{% url 'my_room_ratings' %}">My Ratings</a>
              
              {% endif %}
            </div>
          </div>
          <a class="nav-item nav-link text-warning" href="{% url 'restaurant' %}">Restaurant</a>

          <div class="dropdown ml-3">
            <a style="outline: none;" class="btn  pt-2 text-warning dropdown-toggle-no-caret nav-link"
              id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">Hall</a>
            <div class="dropdown-menu transparent-dropdown" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item nav-link text-warning " href="{% url 'hall_list' %}">View Halls</a>
              {% if user.is_authenticated and request.resolver_match.url_name != 'login' %}
              <a class="dropdown-item nav-link text-warning" href="{% url 'hall_bookings' %}">My Bookings</a>
              {% endif %}
            </div>
          </div>
          <div class="dropdown ml-3">
            <a style="outline: none;" class="btn  pt-2 text-warning dropdown-toggle-no-caret nav-link"
              id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">Fitness</a>
            <div class="dropdown-menu transparent-dropdown" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item nav-link text-warning" href="{% url 'membership_plans' %}">Gym</a>
              {% if user.is_authenticated  %}
              <a class="dropdown-item nav-link text-warning" href="{% url 'my_memberships' %}">My Memberships</a>
              {% endif %}
            </div>
          </div>
          <div class="dropdown ml-3">
            <a style="outline: none;" class="btn  pt-2 text-warning dropdown-toggle-no-caret nav-link"
              id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">Spa & Beauty</a>
            <div class="dropdown-menu transparent-dropdown" aria-labelledby="dropdownMenuButton">
              <a class="nav-item nav-link text-warning" href="{% url 'spa:service_list' %}">View Spa</a>
              {% if user.is_authenticated %}
              <a class="nav-item nav-link text-warning" href="{% url 'spa:booking_list' %}">My Spa Bookings</a>
              {% endif %}
            </div>
          </div>

          <a class="nav-item nav-link text-warning" href="{% url 'contact' %}">Contact</a>

          {% if user.is_authenticated and request.resolver_match.url_name != 'login' %}
          <div class="dropdown ml-3">
            <button style="outline: none;" class="btn p-0 nav-link" type="button" id="dropdownMenuButton"
              aria-haspopup="true" aria-expanded="false">
              {% if user.profile_picture and user.profile_picture.url %}
              <img src="{{ user.profile_picture.url }}" class="rounded-circle" alt="{{ user.username }}"
                style="width: 30px; height: 30px; object-fit: cover;">
              {% else %}
              <img src="{% static 'default_profile_picture.png' %}" class="rounded-circle"
                alt="Default profile picture" style="width: 30px; height: 30px; object-fit: cover;">
              {% endif %}
            </button>
            <div class="dropdown-menu transparent-dropdown" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item text-warning" href="{% url 'profile_detail' user.pk %}">Profile</a>

              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="dropdown-item text-warning text-uppercase">Logout</button>
              </form>
            </div>
          </div>
          {% elif not user.is_authenticated and request.resolver_match.url_name != 'login' %}
          <a href="{% url 'login' %}" class="btn text-warning pb-2 text-uppercase">Login</a>
          {% endif %}
        </div> <!-- navbar-nav -->
      </div> <!-- collapse -->
    </div> <!-- container -->
  </nav> <!-- navbar -->

  {% block content %}
  
  {% endblock content %}

  {% block contents %}
  {% endblock contents %}

  <!-- Footer -->
  <footer class="page-footer font-small text-center text-md-left " style="margin-top: 15rem;">

    <!-- Footer Links -->
    <div class="container py-5">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-4 mx-auto">

          <!-- Links -->
          <h3 class="font-weight-bold text-uppercase mt-3 mb-4 text-warning">Address</h3>

          <div>
            <p class="text-warning">Main Street 123</p>
            <p class="text-warning">Addis Ababa, AA, ETH</p>
            <a href="{% url 'contact' %} "class="text-warning"><small>Get direction</small></a>
          </div>

        </div> <!-- col-md-4 mx-auto -->

        <!-- Grid column -->
        <hr class="clearfix w-100 d-md-none">

        <!-- Grid column -->
        <div class="col-md-4 mx-auto">

          <!-- Links -->
          <h3 class="font-weight-bold text-uppercase mt-3 mb-4 text-warning">Contact</h3>

          <ul class="list-unstyled">
            <li>
              <p class="text-warning"><i class="bi bi-inbox"></i> &ensp;Email &ensp; <a href="mailto:adarhotel33@gmail.com" class="text-warning">adarhotel33@gmail.com</a></p>
            </li >
            <li>
              <p class="text-warning"><i class="bi bi-phone"></i> Phone &ensp;<a href="tel:+251-123-456-789" class="text-warning">+251-123-456-789</a></p>
            </li>
          </ul>

        </div> <!-- col-md-4 mx-auto -->

        <!-- Grid column -->
        <hr class="clearfix w-100 d-md-none">

        <!-- Grid column -->
        <div class="col-md-4 mx-auto">

          <!-- Links -->
          <h3 class="font-weight-bold text-uppercase mt-3 mb-4 text-warning">Follow Us</h3>

          <ul class="list-unstyled">
            <li>
              <a href="#!" class="text-warning"><i class="bi bi-facebook text-warning"></i> Facebook</a>
            </li>
            <li class="text-warning">
              <a href="#!" class="text-warning"><i class="bi bi-twitter text-warning"></i> Twitter</a>
            </li>
            <li>
              <a href="#!" class="text-warning"><i class="bi bi-instagram text-warning"></i> Instagram</a>
            </li>
            <li>
              <a href="#!" class="text-warning"><i class="bi bi-linkedin text-warning"></i> LinkedIn</a>
            </li>
          </ul>

        </div> <!-- col-md-4 mx-auto -->

      </div> <!-- row -->

    </div> <!-- container -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-warning">© 2024 ADAR. All rights reserved.</div>

  </footer>

  
  <!-- Google Translate Element -->
  <div id="google_translate_element"></div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script type="text/javascript">
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({
        pageLanguage: 'en',
        includedLanguages: 'am,,en,es,fr,de,it,pt,ja,ar',
        layout: google.translate.TranslateElement.InlineLayout.SIMPLE,
        autoDisplay: false
      }, 'google_translate_element');
    }
    
  </script>
  
  <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</body>

</html>