HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from room.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('account/', include('accountss.urls')),
    path('admins/', include('admins.urls')),
    path('social/', include('social_media.urls') ),
    path('', home, name='home'),
    path('room/', include('room.urls')),
    path('restaurant/', restaurant, name='restaurant'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('accounts/', include('allauth.urls')),
    path('social/', include('social_django.urls', namespace='social')),
    path('gym/', include('gym.urls')),
    path('', include('paypal.standard.ipn.urls')),
    path('hall/', include('Hall.urls')),
    path('spa/', include('Spa.urls')),
    
    
]


# your existing URL patterns...

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Spa/urls.py
from django.urls import path
from .views import *

app_name = 'spa'

urlpatterns = [
    path('', ServiceListView.as_view(), name='service_list'),
    path('booking/create/', SpaBookingCreateView.as_view(), name='create_booking'),
    path('bookings/', BookingListView.as_view(), name='booking_list'),
    path('booking/cancel/<int:booking_id>/', CancelBookingView.as_view(), name='cancel_booking'),
    path('book/<str:item_type>/<int:item_id>/', SpaBookingCreateView.as_view(), name='spa_booking_create'),
    path('paypal-return/', SpaPayPalReturnView.as_view(), name='spa_paypal_return'),
    path('paypal-cancel/', SpaPayPalCancelView.as_view(), name='spa_paypal_cancel'),
]

Spa/models.py
from django.db import models
from django.db import models
from accountss.models import Custom_user

class SpaService(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='media/', blank=True, null=True) 
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

class SpaPackage(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='media/', blank=True, null=True) 
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

class SpaBooking(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(Custom_user, on_delete=models.CASCADE, null=True, blank=True)
    service = models.ForeignKey(SpaService, null=True, blank=True, on_delete=models.SET_NULL)
    package = models.ForeignKey(SpaPackage, null=True, blank=True, on_delete=models.SET_NULL)
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    amount_due = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    tx_ref = models.CharField(max_length=100, unique=True, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    for_first_name = models.CharField(max_length=100, null=True, blank=True)
    for_last_name = models.CharField(max_length=100, null=True, blank=True)
    for_phone_number = models.CharField(max_length=20, null=True, blank=True)
    for_email = models.EmailField(null=True, blank=True)


    def __str__(self):
        user_display = self.user.username if self.user else self.for_first_name
        service_or_package = self.service if self.service else self.package
        return f"{user_display} - {service_or_package} on {self.appointment_date} at {self.appointment_time}"


class SpaPayment(models.Model):
    PAYMENT_METHOD_CHOICES = (
        ('chapa', 'Chapa'),
        ('paypal', 'PayPal'),
        ('cash', 'Cash'),
    )
    spa_booking = models.OneToOneField(SpaBooking, on_delete=models.CASCADE)
    payment_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100)
    receipt_pdf = models.FileField(upload_to='media/receipts/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default='chapa')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending')

    def __str__(self):
        user_display = self.spa_booking.user.username if self.spa_booking.user else self.spa_booking.full_name
        service_or_package = self.spa_booking.service.name if self.spa_booking.service else self.spa_booking.package.name
        return f"Payment for {user_display} - {service_or_package}"

Spa/views.py
from django.views.generic import ListView, CreateView, View
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import SpaService, SpaPackage, SpaBooking
from .forms import SpaBookingForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from config import BASE_URL
import requests
from django.utils import timezone
import random
import string
from paypalrestsdk import Payment, configure 
from .models import SpaService, SpaPackage, SpaBooking
from .forms import SpaBookingForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from io import BytesIO
import qrcode
import base64
from xhtml2pdf import pisa
import paypalrestsdk
from .models import SpaBooking, SpaPayment
from django.utils.safestring import mark_safe
from django.db.models import Q
import os
from dotenv import load_dotenv

load_dotenv()

chapa_api_key = os.getenv('CHAPA_API_KEY')
paypal_client_id = os.getenv('PAYPAL_CLIENT_ID')
paypal_client_secret = os.getenv('PAYPAL_CLIENT_SECRET')


class ServiceListView(ListView):
    model = SpaService
    template_name = 'spa/spa_services_packages.html'
    context_object_name = 'services'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['packages'] = SpaPackage.objects.all()
        return context





from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
import random
import string
import requests
from paypalrestsdk import Payment, configure

class SpaBookingCreateView(LoginRequiredMixin, FormView):
    form_class = SpaBookingForm
    template_name = 'spa/spa_booking_create.html'

    def get_initial(self):
        initial = super().get_initial()
        item_type = self.kwargs.get('item_type')
        item_id = self.kwargs.get('item_id')

        selected_item = None
        if item_type == 'service':
            selected_item = SpaService.objects.filter(id=item_id).first()
        elif item_type == 'package':
            selected_item = SpaPackage.objects.filter(id=item_id).first()

        if selected_item:
            # Find an existing booking with a pending status for the user
            existing_booking = SpaBooking.objects.filter(
                user=self.request.user,
                service=selected_item if item_type == 'service' else None,
                package=selected_item if item_type == 'package' else None,
                status='pending'
            ).first()

            if existing_booking:
                initial.update({
                    'service': existing_booking.service,
                    'package': existing_booking.package,
                    'appointment_date': existing_booking.appointment_date,
                    'appointment_time': existing_booking.appointment_time,
                    'for_first_name': existing_booking.for_first_name,
                    'for_last_name': existing_booking.for_last_name,
                    'for_email': existing_booking.for_email,
                    'for_phone_number': existing_booking.for_phone_number,
                    'payment_method': 'chapa' if existing_booking.tx_ref.startswith('spa-booking') else 'paypal'
                })

                # Determine if the booking is for self or others based on existing data
                if existing_booking.for_first_name or existing_booking.for_last_name or existing_booking.for_email or existing_booking.for_phone_number:
                    initial['booking_for'] = 'others'
                else:
                    initial['booking_for'] = 'self'

        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item_type = self.kwargs.get('item_type')
        item_id = self.kwargs.get('item_id')

        if item_type == 'service':
            context['item'] = SpaService.objects.filter(id=item_id).first()
        elif item_type == 'package':
            context['item'] = SpaPackage.objects.filter(id=item_id).first()

        return context

    def form_valid(self, form):
        item_type = self.kwargs.get('item_type')
        item_id = self.kwargs.get('item_id')

        if item_type == 'service':
            selected_item = SpaService.objects.filter(id=item_id).first()
        elif item_type == 'package':
            selected_item = SpaPackage.objects.filter(id=item_id).first()
        else:
            selected_item = None

        if selected_item is None:
            messages.error(self.request, 'The item you are trying to book does not exist.')
            return redirect('spa:booking_list')

        appointment_date = form.cleaned_data['appointment_date']
        appointment_time = form.cleaned_data['appointment_time']
        booking_for = form.cleaned_data.get('booking_for')

        # Check for existing booking with the same date and time for the selected item
        existing_booking = SpaBooking.objects.filter(
            user=self.request.user,
            appointment_date=appointment_date,
            appointment_time=appointment_time,
            service=selected_item if item_type == 'service' else None,
            package=selected_item if item_type == 'package' else None,
            status='pending',
        ).first()

        if existing_booking:
            if existing_booking.for_first_name == form.cleaned_data.get('for_first_name') and \
                existing_booking.for_last_name == form.cleaned_data.get('for_last_name') and \
                existing_booking.for_email == form.cleaned_data.get('for_email') and \
                existing_booking.for_phone_number == form.cleaned_data.get('for_phone_number'):
                # If the existing booking matches the current form data, proceed to payment
                return self.redirect_to_payment(existing_booking, form.cleaned_data['payment_method'])
            else:
                # Otherwise, it is a double booking attempt
                messages.error(self.request, 'You have an identical booking.')
                return self.form_invalid(form)

        # Check if there are already 5 bookings for the same service/package, date, and time
        total_bookings = SpaBooking.objects.filter(
            appointment_date=appointment_date,
            appointment_time=appointment_time,
            service=selected_item if item_type == 'service' else None,
            package=selected_item if item_type == 'package' else None,
            status='pending',
        ).count()

        if total_bookings >= 5:
            # If there are already 5 bookings for the same service/package, date, and time
            messages.error(self.request, 'This time slot is fully booked. Please select a different time.')
            return self.form_invalid(form)
        
        # Create new booking
        spa_booking = self.create_booking(form, selected_item, item_type)

        # Handle payment
        return self.redirect_to_payment(spa_booking, form.cleaned_data['payment_method'])

    def create_booking(self, form, selected_item, item_type):
        booking_for = form.cleaned_data.get('booking_for')

        spa_booking = SpaBooking.objects.create(
            user=self.request.user,
            service=selected_item if item_type == 'service' else None,
            package=selected_item if item_type == 'package' else None,
            appointment_date=form.cleaned_data['appointment_date'],
            appointment_time=form.cleaned_data['appointment_time'],
            amount_due=selected_item.price,
            for_first_name=form.cleaned_data['for_first_name'] if booking_for == 'others' else '',
            for_last_name=form.cleaned_data['for_last_name'] if booking_for == 'others' else '',
            for_phone_number=form.cleaned_data['for_phone_number'] if booking_for == 'others' else '',
            for_email=form.cleaned_data['for_email'] if booking_for == 'others' else '',
            status='pending',
            tx_ref=self.generate_tx_ref(),
        )
        return spa_booking

    def generate_tx_ref(self):
        return f"spa_booking-{self.request.user.username}-tx-{''.join(random.choices(string.ascii_lowercase + string.digits, k=10))}"

    def redirect_to_payment(self, booking, payment_method):
        if payment_method == 'chapa':
            return self.initiate_chapa_payment(booking)
        elif payment_method == 'paypal':
            return self.initiate_paypal_payment(booking)
        else:
            messages.error(self.request, 'Invalid payment method selected.')
            return redirect('spa:booking_list')

    def initiate_chapa_payment(self, spa_booking):
        amount = str(spa_booking.amount_due)
        print(amount)
        tx_ref = self.generate_tx_ref()
        spa_booking.tx_ref=tx_ref
        spa_booking.save()

        url = "https://api.chapa.co/v1/transaction/initialize"
        redirect_url = f'{BASE_URL}/spa/bookings'
        webhook_url = f'{BASE_URL}room/chapa-webhook/'

        payload = {
            "amount": amount,
            "currency": "ETB",
            "email": self.request.user.email,
            "first_name": self.request.user.first_name,
            "last_name": self.request.user.last_name,
            "phone_number": self.request.user.phone_number,
            "redirect_url": self.request.build_absolute_uri(redirect_url),
            "tx_ref": tx_ref,
            "callback_url": webhook_url,
        }
        headers = {
            'Authorization': f'Bearer {chapa_api_key}',
            'Content-Type': 'application/json'
        }
        print(headers)

Spa/templates/spa/booking_confirmation_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Spa Booking Confirmation</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f6f6f6;
        }
        .container {
            width: 100%;
            max-width: 900px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .header {
            background-color: #f9fd00;
            color: #000000;
            text-align: center;
            padding: 20px 0;
            border-radius: 8px 8px 0 0;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .content {
            padding: 20px;
            color: #333333;
        }
        .content p {
            margin: 0 0 10px;
        }
        .button {
            display: inline-block;
            padding: 10px 20px;
            margin: 20px 0;
            font-size: 16px;
            color: white;
            background-color: #4CAF50;
            text-decoration: none;
            border-radius: 5px;
            text-align: center;
        }
        .footer {
            text-align: center;
            padding: 10px 0;
            font-size: 12px;
            color: #777777;
            border-top: 1px solid #dddddd;
            margin-top: 20px;
        }
        .row {
            width: 100%;
            margin-bottom: 10px;
            overflow: hidden;
        }
        .col-6 {
            float: left;
            width: 50%;
        }
        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }
        strong {
            display: inline-block;
            margin-right: 5px;
        }
        .centered-button {
            text-align: center;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>ADAR Hotel Spa Booking Confirmation</h1>
        </div>
        <div class="content">
            <h3>Dear {% if spa_booking.user.get_full_name %}{{ spa_booking.user.get_full_name }}{% else %}{{ spa_booking.for_first_name }}{% endif %},</h3>
            <p>Your spa booking has been successfully confirmed!</p>
            <p><strong>Booking Details</strong></p>
            <div class="row mb-2 clearfix">
                <div class="col-6"><strong>Service</strong></div>
                <div class="col-6">{% if spa_booking.service %}{{ spa_booking.service.name }} {% else %} {{spa_booking.package.name }}{% endif %}</div>
            </div>
            <div class="row mb-2 clearfix">
                <div class="col-6"><strong>Appointment Date</strong></div>
                <div class="col-6">{{ spa_booking.appointment_date }}</div>
            </div>
            <div class="row mb-2 clearfix">
                <div class="col-6"><strong>Appointment Time</strong></div>
                <div class="col-6">{{ spa_booking.appointment_time }}</div>
            </div>
            <div class="row mb-2 clearfix">
                <div class="col-6"><strong>Amount</strong></div>
                <div class="col-6">{{ spa_booking.amount_due }} ETB</div>
            </div>
            <div class="row mb-2 clearfix">
                <div class="col-6"><strong>Status</strong></div>
                <div class="col-6">{{ spa_booking.status }}</div>
            </div>
            <div class="row mb-2 clearfix">
                <div class="col-6"><strong>For</strong></div>
                <div class="col-6">{% if spa_booking.for_first_name %}{{ spa_booking.for_first_name }} {{ spa_booking.for_last_name }}{% else %}{{ spa_booking.user.first_name }}{% endif %}</div>
            </div>
            {% if booking_url %}
            <div class="centered-button">
                <a href="{{ booking_url }}" class="button">View Booking</a>
            </div>
            {% endif %}
        </div>
        <div class="footer">
            <p>Thank you for choosing our hotel spa!</p>
            <p>For any assistance, please contact us at <a href="mailto:adarhotel33@gmail.com">adarhotel33@gmail.com</a></p>
        </div>
    </div>
</body>
</html>

Spa/templates/spa/booking_confirmation_template_receipt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Spa Booking Receipt</title>
    <style>
        body { font-family: Calibri, Arial, sans-serif; }
        .header {
            background-color: #fad500;
            color: rgb(0, 0, 0);
            text-align: center;
            padding: 15px 0;
            font-size: larger;
            margin-bottom: 20px;
            border-radius: 10px 10px 0 0;
        }        
        .details { margin-bottom: 20px; font-size: large; }
        .footer { text-align: center; font-size: 12px; }
        .qr-code { text-align: center; margin: 20px 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Spa Booking Receipt</h1>
    </div>
    <div class="details">
        <p><strong>Booking ID:</strong> {{ spa_booking.id }}</p>
        <p><strong>User:</strong> {% if spa_booking.user.get_full_name %}{{ spa_booking.user.get_full_name }}{% else %}{{ spa_booking.for_first_name }}{% endif %}</p>
        <p><strong>Service/Package:</strong>{% if spa_booking.service %}{{ spa_booking.service.name }} {% else %} {{spa_booking.package.name }}{% endif %}</p>
        <p><strong>Appointment Date:</strong> {{ spa_booking.appointment_date }}</p>
        <p><strong>Appointment Time:</strong> {{ spa_booking.appointment_time }}</p>
        <p><strong>Amount</strong> {{ spa_booking.amount_due }}ETB</p>
        {% if spa_booking.for_first_name %}
            <p><strong>For:</strong> {{ spa_booking.for_first_name }} {{ spa_booking.for_last_name }}</p>
            <p><strong>Email:</strong> {{ spa_booking.for_email }}</p>
            <p><strong>Phone Number:</strong> {{ spa_booking.for_phone_number }}</p>
        {% endif %}
    </div>
    <div class="qr-code">
        <img src="{{ qr_code_data }}" alt="QR Code">
    </div>
    <div class="footer">
        <p>Thank you for choosing our hotel spa!</p>
        <p>For any assistance, please contact us at support@hotelspa.com</p>
    </div>
</body>
</html>

Spa/templates/spa/booking_list.html
{% extends "accountss/base.html" %}

{% block title %}Your Spa Bookings{% endblock %}

{% block content %}
<br>
<div class="container mt-5">
    <h3 class="text-center mb-5 font-weight-bold">Your Spa Bookings</h3>
    <!-- Centered dismissable alert -->
<div class="container mt-3 mb-2">
    <div class="alert alert-warning alert-dismissible fade show text-center " role="alert">
        <i class="bi bi-info-circle"></i>&ensp;Pending bookings will be cancelled automatically if payment isn't completed within two days of creating the booking.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>

    <!-- Filter Button Group -->
    <div class="btn-group d-flex justify-content-center mb-4" role="group" aria-label="Filter Bookings">
        <a href="{% url 'spa:booking_list' %}" class="btn rounded btn-sm mx-1 {% if not request.GET.status %}btn-warning{% else %}btn-outline-dark{% endif %}">All</a>
        <a href="{% url 'spa:booking_list' %}?status=pending" class="btn rounded btn-sm mx-1 {% if request.GET.status == 'pending' %}btn-warning{% else %}btn-outline-dark{% endif %}">Pending</a>
        <a href="{% url 'spa:booking_list' %}?status=confirmed" class="btn rounded btn-sm mx-1 {% if request.GET.status == 'confirmed' %}btn-warning{% else %}btn-outline-dark{% endif %}">Confirmed</a>
        <a href="{% url 'spa:booking_list' %}?status=cancelled" class="btn rounded btn-sm mx-1 {% if request.GET.status == 'cancelled' %}btn-warning{% else %}btn-outline-dark{% endif %}">Cancelled</a>
    </div>

    <div class="container" style="margin-top: 1rem;">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-dismissible text-center mt-5 alert-{{ message.tags }}">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    
    <div class="row">
        {% if bookings %}
            {% with filter_status=request.GET.status %}
                {% for booking in bookings %}
                    {% if not filter_status or booking.status == filter_status %}
                        <div class="col-md-6 mb-4">
                            <div class="card h-100 rounded shadow">
                                <div class="card-body">
                                    <h5 class="card-title"><strong><i class="bi bi-list-ol"></i>&ensp; {% if booking.service %}{{ booking.service.name }}  {% else %} {{ booking.package.name }} {% endif %}</strong></h5>
                                    <div class="row mb-2">
                                        <div class="col-sm-6 text-left"><strong><i class="bi bi-calendar-plus"></i>&ensp;Appointment Date</strong></div>
                                        <div class="col-sm-6 text-center">{{ booking.appointment_date }}</div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col-sm-6 text-left"><strong><i class="bi bi-clock"></i>&ensp;Time</strong></div>
                                        <div class="col-sm-6 text-center">{{ booking.appointment_time }}</div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col-sm-6 text-left"><strong><i class="bi bi-cash"></i>&ensp;Amount</strong></div>
                                        <div class="col-sm-6 text-center">{% if booking.service %}{{ booking.service.price}}{% else %}{{booking.package.price}}{% endif %} ETB</div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col-sm-6 text-left"><strong><i class="bi bi-info-circle"></i>&ensp;Status</strong></div>
                                        <div class="col-sm-6 text-center">{{ booking.get_status_display }}</div>
                                    </div>
                                    <div class="d-flex justify-content-center m-3">
                                    {% if booking.status == 'pending' %}
                                        {% if booking.service %}
                                            <a href="{% url 'spa:spa_booking_create' 'service' booking.service.id %}" class="btn btn-sm btn-success rounded mr-2">Pay Now</a>
                                        {% elif booking.package %}
                                            <a href="{% url 'spa:spa_booking_create' 'package' booking.package.id %}" class="btn btn-sm btn-success rounded mr-2">Pay Now</a>
                                        {% endif %}
                                    {% endif %}
                                    {% if booking.status != 'cancelled' %}
                                    <button type="button" class="btn btn-sm btn-danger rounded" data-toggle="modal" data-target="#cancelModal{{ booking.pk }}">
                                        Cancel Booking
                                    </button>
                                    {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Cancel Modal -->
                        <div class="modal fade" id="cancelModal{{ booking.pk }}" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel{{ booking.pk }}" aria-hidden="true">
                            <div class="modal-dialog rounded" role="document">
                                <div class="modal-content border-0">
                                    <div class="modal-header border-0">
                                        <h5 class="modal-title font-weight-bold" id="cancelModalLabel{{ booking.pk }}">Cancel Booking</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body font-weight-bold">
                                        Are you sure you want to cancel your booking for {% if booking.service %}{{ booking.service.name }}  {% else %} {{ booking.package.name }} {% endif %}?
                                    </div>
                                    <div class="modal-footer border-0">
                                        <form method="post" action="{% url 'spa:cancel_booking' booking.id %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-sm rounded btn-danger">Confirm</button>
                                        </form>
                                        <button type="button" class="btn btn-sm rounded btn-secondary" data-dismiss="modal">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endwith %}
        {% else %}
            <div class="container d-flex justify-content-center">
                <div class="alert alert-warning rounded mt-3" role="alert">
                    <h6 class="text-center"><i class="bi bi-info-circle"></i>&ensp;No bookings found</h6>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}