HMS/urls.py
from django.contrib import admin
from django.urls import path, include
from room.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('account/', include('accountss.urls')),
    path('admins/', include('admins.urls')),
    path('social/', include('social_media.urls') ),
    path('', home, name='home'),
    path('room/', include('room.urls')),
    path('restaurant/', restaurant, name='restaurant'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('accounts/', include('allauth.urls')),
    path('social/', include('social_django.urls', namespace='social')),
    path('gym/', include('gym.urls')),
    path('', include('paypal.standard.ipn.urls')),
    path('hall/', include('Hall.urls')),
    path('spa/', include('Spa.urls')),
    
    
]


# your existing URL patterns...

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hall/urls.py
# urls.py

from django.urls import path
from .views import *

urlpatterns = [
    path('', HallListView.as_view(), name='hall_list'),
    path('hall/<int:pk>/', HallDetailView.as_view(), name='hall_detail'),
    path('my-bookings/', BookingListView.as_view(), name='hall_bookings'),
    path('halls/<int:pk>/check-availability/', CheckAvailabilityView.as_view(), name='check_availability'),
    path('halls/<int:pk>/book/', BookingView.as_view(), name='book_hall'),
    path('paypal-return/', PayPalReturnView.as_view(), name='paypal_return'),
    path('paypal-cancel/', PayPalCancelView.as_view(), name='paypal_cancel'),
    path('payment/<int:pk>/', PaymentView.as_view(), name='payment_page'),
    path('hall/bookings/<int:pk>/cancel/', HallBookingCancelView.as_view(), name='hall_booking_cancel'),
]

room/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', RoomListView.as_view(), name='rooms'),
    path('<int:pk>/', RoomDetailView.as_view(), name='room_detail'),
    path('my-bookings/', BookingListView.as_view(), name='bookings'),
    path('<int:room_id>/book/', BookingCreateView.as_view(), name='booking_create'),
    path('booking/<int:booking_id>/pay/', PaymentView.as_view(), name='payment_create'),
    path('booking/extend/<int:booking_id>/', BookingExtendView.as_view(), name='booking_extend'),
    path('payment/extend/<int:booking_id>/', PaymentExtendView.as_view(), name='payment_extend'),
    path('booking/<int:pk>/cancel/', BookingCancelView.as_view(), name='booking_cancel'),
    path('chapa-webhook/', ChapaWebhookView.as_view(), name='chapa_webhook'),
    path('booking/<int:booking_id>/upload_receipt/', ReceiptUploadView.as_view(), name='upload_receipt'),
    path('paypal-return/', PayPalReturnView.as_view(), name='paypal_return'),
    path('paypal-cancel/', PayPalCancelView.as_view(), name='paypal_cancel'),
    path('rating/<int:pk>/ratings/', RoomRatingListView.as_view(), name='room_ratings'),
    path('rating/<int:pk>/add_rating/', AddRoomRatingView.as_view(), name='add_room_rating'),
    path('rating/edit/<int:rating_id>/', EditRoomRatingView.as_view(), name='edit_room_rating'),
    path('rating/delete/<int:rating_id>/', DeleteRoomRatingView.as_view(), name='delete_room_rating'),
    path('my-ratings/', UserRoomRatingsListView.as_view(), name='my_room_ratings'),
    path('rating/test/ratings/<int:pk>/', test_view, name='test_view'),

]

Hall/models.py
from django.db import models
from accountss.models import Custom_user as User
from django.utils import timezone
import datetime

class Hall_Category(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Hall(models.Model):
    Hall_STATUS_CHOICES = (
        ('available', 'Available'),
        ('booked', 'Booked'),
    )
    hall_type = models.ForeignKey(Hall_Category, on_delete=models.CASCADE, default=1)
    hall_number = models.CharField(max_length=20, default='000')
    description = models.TextField()
    price_per_hour = models.DecimalField(max_digits=10, decimal_places=2)
    capacity = models.IntegerField()
    image = models.ImageField(upload_to='media/hall_images/', blank=True)
    floor = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=Hall_STATUS_CHOICES, default='available')


    def __str__(self):
        return f"{self.hall_number} - {self.hall_type}"

class Hall_Booking(models.Model):
    Booking_STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, null=True)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100,blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(default=datetime.time(6, 0),null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    amount_due = models.DecimalField(max_digits=10, decimal_places=2)
    is_paid = models.BooleanField(default=False)
    occupied = models.BooleanField(default=False)
    email2 = models.EmailField(null=True, blank=True)
    id_image = models.ImageField(upload_to='media/id_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    tx_ref = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=20, choices=Booking_STATUS_CHOICES, default='pending')

    def __str__(self):
        user_display = self.user.username if self.user else self.full_name
        return f"{user_display} - {self.hall.hall_type}"




class Hall_Payment(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    )
    PAYMENT_METHOD_CHOICES = (
        ('chapa', 'Chapa'),
        ('paypal', 'PayPal'),
        ('cash', 'Cash'),
    )
    booking = models.OneToOneField(Hall_Booking, on_delete=models.CASCADE)
    payment_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    receipt_pdf = models.FileField(upload_to='media/receipts/', blank=True, null=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default='chapa')
    
    def __str__(self):
        return f"Payment {self.id} - {self.status}"

room/models.py
from django.db import models
from django.utils import timezone
from accountss.models import Custom_user 
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import date
from django.db.models import Q

class Category(models.Model):
    name = models.CharField(max_length=20)
    rank = models.IntegerField(default=0)

    def __str__(self):
        return self.name
class Room(models.Model):
    ROOM_STATUS_CHOICES = (
        ('vacant', 'Vacant'),
        ('occupied', 'Occupied'),
    )

    room_number = models.CharField(max_length=20)
    room_type = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    price_per_night = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    room_status = models.CharField(max_length=20, choices=ROOM_STATUS_CHOICES, default='vacant')
    room_image = models.ImageField(upload_to='media/room_images/', blank=True)
    capacity = models.IntegerField()
    description = models.TextField(blank=True)
    floor = models.IntegerField()

    def __str__(self):
        return f"{self.room_number} - {self.room_type}"

class Booking(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('cancelled', 'Cancelled'),
    )
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(Custom_user, on_delete=models.CASCADE, null=True, blank=True) 
    full_name = models.CharField(max_length=100,null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    original_booking_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    booking_extend_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    email2 = models.EmailField(null=True, blank=True)
    id_image = models.ImageField(upload_to='media/id_images/', blank=True, null=True)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    extended_check_out_date = models.DateField(null=True, blank=True)  # New field for extended checkout date
    created_at = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)
    checked_in = models.BooleanField(default=False)
    checked_out = models.BooleanField(default=True)
    guests = models.IntegerField(null=True, blank=True)
    tx_ref = models.CharField(max_length=100, unique=True, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    def calculate_additional_amount(self):
        if self.extended_check_out_date and self.extended_check_out_date > self.check_out_date:
            extended_days = (self.extended_check_out_date - self.check_out_date).days
            return self.room.price_per_night * extended_days
        else:
            return 0

    def save(self, *args, **kwargs):
        self.full_clean()  # Call clean method to perform validations

        if self.pk is None:  # Only calculate amount if it's a new instance
            # Calculate duration of stay
            duration = (self.check_out_date - self.check_in_date).days
            # Calculate amount based on price per night and duration
            self.original_booking_amount = self.room.price_per_night * duration
        # Perform regular save with validation
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        room = self.room
        super().delete(*args, **kwargs)

    
    def has_receipt(self):
        return Receipt.objects.filter(booking=self).exists()

    def __str__(self):
        user_display = self.user.username if self.user else self.full_name
        return f"Booking for {user_display} in {self.room} from {self.check_in_date} to {self.check_out_date}"





class Payment(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    )
    PAYMENT_METHOD_CHOICES = (
        ('chapa', 'Chapa'),
        ('paypal', 'PayPal'),
        ('cash', 'Cash'),
    )
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE)
    payment_date = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    receipt_pdf = models.FileField(upload_to='media/receipts/', blank=True, null=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default='chapa')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.status == 'completed':
            self.booking.is_paid = True
            self.booking.save()
        elif self.status == 'failed':
            self.booking.delete()

    def __str__(self):
        if self.booking.user:
            user_display = self.booking.user.username
        else:
            user_display = f"{self.booking.full_name}"
        return f"Payment for {user_display} - {self.payment_method}"

class Receipt(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE)
    file = models.FileField(upload_to='media/receipts/')



class RoomRating(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(Custom_user, on_delete=models.CASCADE)
    rating = models.IntegerField()
    review = models.TextField()
    rating_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.room} - {self.rating}"

Hall/forms.py
# forms.py

from django import forms
from .models import Hall_Booking
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone


class BookingForm(forms.ModelForm):
    class Meta:
        model = Hall_Booking
        fields = ['start_date', 'end_date', 'start_time', 'end_time', 'amount_due']  # Adjust fields as necessary
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
            'start_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),
        }


from datetime import timedelta, datetime

class CheckAvailabilityForm(forms.Form):
    start_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    end_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    start_time = forms.TimeField(widget=forms.TextInput(attrs={'type': 'time'}))
    end_time = forms.TimeField(widget=forms.TextInput(attrs={'type': 'time'}))

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')
        
        # Check if start date is in the past
        if start_date and start_date < timezone.now().date():
            raise ValidationError("Start date cannot be in the past.")

        # Check if end date is in the past
        if end_date and end_date < timezone.now().date():
            raise ValidationError("End date cannot be in the past.")

        # Check if end date is before start date
        if end_date and end_date < start_date:
            raise ValidationError("End date cannot be before start date.")

        # Check if end time is before start time when dates are the same
        if end_date == start_date and end_time < start_time:
            raise ValidationError("End time cannot be before start time when start and end dates are the same.")

        # Check if the gap between start time and end time is at least one hour
        if end_date == start_date:
            start_datetime = datetime.combine(start_date, start_time)
            end_datetime = datetime.combine(end_date, end_time)
            if end_datetime - start_datetime < timedelta(hours=1):
                raise ValidationError("The gap between start time and end time must be at least one hour.")

        return cleaned_data

room/forms.py
from django import forms
from .models import Booking, Payment, RoomRating
from datetime import date
from django import forms
from .models import Booking
from django.utils import timezone
from django.core.exceptions import ValidationError

class BookingExtendForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['extended_check_out_date']
        widgets = {
            'extended_check_out_date': forms.DateInput(attrs={'type': 'date'}),
        }


class BookingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.room = kwargs.pop('room', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Booking
        fields = ['check_in_date', 'check_out_date', 'guests']
        widgets = {
            'check_in_date': forms.DateInput(attrs={'type': 'date'}),
            'check_out_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def clean_guests(self):
        guests = self.cleaned_data.get('guests')
        room_capacity = self.room.capacity

        if guests < 1:
            raise ValidationError('The number of guests must be at least 1.')
        elif guests > room_capacity:
            raise ValidationError(f'The number of guests cannot exceed the room capacity which is {self.room.capacity} for this room.')

        return guests

    def clean_check_in_date(self):
        check_in_date = self.cleaned_data.get('check_in_date')
        if check_in_date < timezone.now().date():
            raise ValidationError('Check-in date cannot be in the past.')
        return check_in_date

    def clean(self):
        cleaned_data = super().clean()
        check_in_date = cleaned_data.get('check_in_date')
        check_out_date = cleaned_data.get('check_out_date')

        if check_in_date and check_out_date:
            if check_out_date <= check_in_date:
                raise ValidationError('Check-out date must be after the check-in date.')

            # Check for room availability
            existing_bookings = Booking.objects.filter(
                room=self.room,
                status__in=['pending', 'confirmed'],
                check_in_date__lt=check_out_date,
                check_out_date__gt=check_in_date
            )

            if existing_bookings.exists():
                raise ValidationError('The room is booked for the selected dates. Please choose different dates.')

        return cleaned_data

        

class RoomRatingForm(forms.ModelForm):
    class Meta:
        model = RoomRating
        fields = ['rating', 'review']
        widgets = {
            'rating': forms.NumberInput(attrs={'min': 1, 'max': 5}),
            'review': forms.Textarea(attrs={'rows': 4}),
        }

admins/templates/admins/booking_detail.html
{% extends 'admins/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-6 mt-5 mb-5">
            <img src="{% if object.room.room_image %}{{ object.room.room_image.url }}{% else %}https://bootdey.com/img/Content/avatar/avatar7.png{% endif %}" alt="{{ object.room.room_type }}" class="img-fluid rounded" style="width: 600px; height: 400px; object-fit: cover;">
        </div>
        <div class="col-md-6 mt-5 mb-4">
            <div class="card shadow-lg rounded">
                <div class="card-body">
                    <h3 class="card-title font-weight-bold"><i class="bi bi-list-ol"></i>&ensp;{{ object.room.room_number }} &emsp; {{ object.room.room_type }} Suite</h3>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-person"></i>&ensp;Customer Name</strong>
                            <span>{% if booking.user%} {{ booking.user.get_full_name }}{% else %}{{ booking.full_name}}{% endif %}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-tag"></i>&ensp;Total Amount</strong>
                            <span>ETB {{ object.total_amount }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-tag"></i>&ensp;Booking Extend Amount</strong>
                            <span>ETB {{ object.booking_extend_amount }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-calendar-check"></i>&ensp;Check In Date</strong>
                            <span>{{ object.check_in_date }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-calendar-x"></i>&ensp;Check Out Date</strong>
                            <span>{{ object.check_out_date }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-calendar-plus"></i>&ensp;Extended Check Out Date</strong>
                            <span>{{ object.extended_check_out_date|default:"-" }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-cash-stack"></i>&ensp;Paid</strong>
                            <span>{{ object.is_paid }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-people-fill"></i>&ensp;Guests</strong>
                            <span>{{ object.guests }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-info-circle"></i>&ensp;Status</strong>
                            <span>{{ object.get_status_display }}</span>
                        </li>
                    </ul>
                    <div class="mt-3 d-flex justify-content-center">
                        <a href="{% url 'admins:booking_list' %}" class="btn btn-sm btn-secondary rounded">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admins/templates/admins/booking_form.html
{% extends 'admins/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card shadow-sm w-100 w-md-75 mt-4">
        <h5 class="card-title text-center mb-3 mt-3"><strong>Create Booking</strong></h5>
        <div class="card-body">
            <form method="post" class="d-flex flex-column align-items-center">
                {% csrf_token %}
                {% if form.non_field_errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {% for error in form.non_field_errors %}
                        {{ error }}<br>
                    {% endfor %}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% for field in form %}
                    <div class="mb-3 w-100 w-md-75">
                        <label class="mb-1 font-weight-bold" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:"form-control rounded" }}
                        {% if field.errors %}
                            <div class="alert alert-danger mt-2">
                                {{ field.errors|first }}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="d-flex justify-content-around w-100 w-md-50 mt-3 mb-5">
                    <button type="submit" class="btn btn-sm btn-primary w-45">Save</button>
                    <a href="{% url 'admins:booking_list' %}" class="btn btn-sm btn-secondary w-45">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

admins/templates/admins/hall_booking_update_form.html
{% extends 'admins/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-4 mb-4">
    <div class="card shadow-sm mx-auto" style="max-width: 100%;">

        <h5 class="card-title text-center mb-3 font-weight-bold"><strong>Update Booking</strong></h5>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data" class="d-flex flex-column align-items-stretch">
                {% csrf_token %}
                {% if form.non_field_errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {% for error in form.non_field_errors %}
                        {{ error }}<br>
                    {% endfor %}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                
                {% for field in form %}
                    <!-- Conditional logic for id_image -->
                    {% if field.name == 'id_image' %}
                        {% if not form.instance.id_image %}
                            <div class="mb-3">
                                <label class="form-label" for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
                                {{ field|add_class:"form-control rounded" }}
                                {% if field.errors %}
                                    <div class="alert alert-danger mt-2">
                                        {{ field.errors|first }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% else %}
                        <div class="mb-3">
                            <label class="form-label" for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
                            {{ field|add_class:"form-control rounded" }}
                            {% if field.errors %}
                                <div class="alert alert-danger mt-2">
                                    {{ field.errors|first }}
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
                
                <div class="d-flex flex-column flex-md-row justify-content-center mt-3">
                    <button type="submit" class="btn btn-primary rounded mb-2 btn-sm mb-md-0 w-100 w-md-auto">Save</button>
                    <a href="{% url 'admins:hall_booking_list' %}" class="btn btn-sm btn-secondary rounded w-100 w-md-auto ms-md-2">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

admins/templates/admins/membership_not_found.html
<!-- admins/booking_not_found.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Membership Not Found</title>
</head>
<body>
    <h1>Membership Not Found</h1>
    <p>The membership you are trying to verify does not exist.</p>
    <a href="{% url 'admins:admin_dashboard' %}">Return to Home</a>
</body>
</html>

admins/templates/admins/receptionist_form.html
{% extends 'admins/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-4 mb-4">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h5 class="card-title text-center mb-4">
                        <strong>
                            {% if form.instance.pk %}Update Receptionist{% else %}Create Receptionist{% endif %}
                        </strong>
                    </h5>
                    <form method="post" enctype="multipart/form-data" class="d-flex flex-column">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}<br>
                            {% endfor %}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endif %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label class="form-label font-weight-bold" for="{{ field.id_for_label }}">
                                    <strong>{{ field.label }}</strong>
                                </label>
                                {{ field|add_class:"form-control rounded" }}
                                {% if field.errors %}
                                    <div class="alert alert-danger mt-2">
                                        {{ field.errors|first }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-flex flex-column flex-md-row justify-content-center mt-3">
                            <button type="submit" class="btn btn-primary mb-2 mb-md-0 me-md-2">
                                {% if form.instance.pk %}Update{% else %}Create{% endif %}
                            </button>
                            <a href="{% url 'admins:receptionist_list' %}" class="btn btn-secondary">
                                Back to List
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

admins/templates/admins/spa_service_form.html
{% extends 'admins/base.html' %}
{% block content %}
{% load widget_tweaks %}
<div class="container mt-3">
    {% if messages %}
        <div class="container">
            {% for message in messages %}
                <div class="alert alert-dismissible text-center mt-5 alert-{{ message.tags }} rounded">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>


<div class="container mt-4 mb-4">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title text-center mb-4"><strong>Create/Edit Spa Service</strong></h5>
                    <form method="post" enctype="multipart/form-data" class="d-flex flex-column">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label class="form-label" for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
                                {{ field|add_class:"form-control rounded" }}
                                {% if field.help_text %}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="alert alert-danger mt-2">
                                        {{ field.errors|first }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}

                        <div class="d-flex flex-column flex-md-row justify-content-center mt-3">
                            <button type="submit" class="btn btn-primary mb-2 mb-md-0 me-md-2">Save</button>
                            <a href="{% url 'admins:spa_service_list' %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}